### ISSUE TITLE
Make Port of WebApp Configurable

### ISSUE THREAD

**Issue by c-thiel** [airbytehq/helm-charts#11]
Currently the Port of the WebApp is Hardcoded to 80:

https://github.com/airbytehq/airbyte-platform/blob/306f8fb5fb154d9f82c97673abc4ae031d79c968/charts/airbyte-webapp/templates/deployment.yaml#L139

As long as we run the webapp as root user this doesn't matter too much. However, on pretty much every prod kubernetes cluster running images as root is prohibited. To address the underlying issue in the pod, the following issue exists. https://github.com/airbytehq/airbyte/issues/11772

Once we swith the webapp user to be non-root, we won't be able to use port 80 anymore.

It would thus be great if we could make the port for the service configurable. A reasonable default would be 8080.

**Comment by davinchia** [comment]
Migrated to https://github.com/airbytehq/airbyte/issues/25188.
