### ISSUE TITLE
0.45.5 release tries to pull unavailable image

### ISSUE THREAD

**Issue by vrfn** [airbytehq/helm-charts#12]
The Helm chart released yesterday (v0.45.5) seems to contain an error: the `connector-builder-server` Deployment tries to pull the image `connector-atelier-server:0.42.1` which does not exist. The correct image is `connector-builder-server:0.42.1`. This image is available on Docker Hub, unlike the `connector-atelier-server:0.42.1` image. 

The incorrect image is set in the default `values.yaml`.

**Comment by vrfn** [comment]
This issue is still blocking all new Helm chart deploys, also on the new 0.45.8 Helm chart version

**Comment by girarda** [comment]
@vrfn the image has been published https://hub.docker.com/layers/airbyte/connector-atelier-server/0.42.1/images/sha256-4ca22422413712f56994c59d49f55c17d7bdb172b0a34aabd28e59dd059f7936?context=repo
