### ISSUE TITLE
Removing old versions while having issues with the newly released version

### ISSUE THREAD

**Issue by NipunaPrashan** [airbytehq/helm-charts#3]
Hi Team,

We were using working 0.36.0 versions for airbyte, and now suddenly showed up all the previous versions are cleaned keeping the newest one. Moreover, the current one has bugs and check the current issues. We are using airbyte helm charts in our dev and staging systems and working fine. 

Would you please keep at least few previous versions before deleting all at ones. Then we can switch gradually to a working version.

Thank you.

**Comment by NipunaPrashan** [comment]
@xpuska513 please consider the request as this is not GA available yet.

**Comment by milesarmstrong** [comment]
Agreed, @xpuska513 please keep the historical working helm charts at least until the various issues (https://github.com/airbytehq/airbyte/issues/16587, https://github.com/airbytehq/airbyte/issues/16586 are the ones I know about) introduced in https://github.com/airbytehq/airbyte/pull/16131 are fixed.

**Comment by NipunaPrashan** [comment]
> And please tag your chart version in this repo.

0.36.0

**Comment by xpuska513** [comment]
Hi @milesarmstrong, @NipunaPrashan, the issue with versioning should be fixed now(the release process got finally updated), so now there should be no more issues with specific version disappearance

**Comment by davinchia** [comment]
Close as resolved.
