### ISSUE TITLE
Changelogs and Documentation 

### ISSUE THREAD

**Issue by HaddadJoe** [airbytehq/helm-charts#5]
It's really hard to navigate this repo without any changelogs or documentation.

Some previously released versions got deleted, https://github.com/airbytehq/helm-charts/commit/bf7d920323e07be37e1a6f432558ca4e484bad70. Where do we go from here if we were using one of these versions (0.42.0)?

it would be much more useful if there's a changelog when items are released and deleted please. I see some automatic deployments are happening to coincide with the releases of the [airbyte repo](https://github.com/airbytehq/airbyte/). What about versions in the helm charts that are not in the airbyte repo? For example `v0.40.12`

Thanks for the help!

**Comment by navi86** [comment]
One more thing, can you update documentation how long charts will be exist ? Usually chart is available 1-2 years, but here it looks like are preserved about 15 days(currently)
Moreover, what chart version "0.40.12" is the latest one and not chart with version "0.41.2" ?

**Comment by davinchia** [comment]
Hi, this repository really only exists to back up https://artifacthub.io/packages/helm/airbyte/airbyte. 

I will update the readme to make this obvious.

As of this comment, we do not have a policy of sweeping charts, so you can expect them to exists indefinitely.
