### ISSUE TITLE
airbyte-env not found

### ISSUE THREAD

**Issue by gajus** [airbytehq/helm-charts#7]
Sometimes `%-airbyte-env` is not created resulting in pods failing with an error saying that airbyte-env cm is not found.

Re-deploying Helm chart several times fixed it in our case, which appears to indicate some sort of a race condition.

In our particular case, it is the `contra-airbyte-cron-ccd97bd95-v6kbt` pod that fails with an error:

> Error: configmap "contra-airbyte-airbyte-env" not found

Don't have more context beyond this since I was not able to reproduce this consistently.

**Comment by davinchia** [comment]
This is slightly old so I'm going to close this. Please open this issue in the main airbyte repo if it still happens!
