### ISSUE TITLE
RUN_DATABASE_MIGRATION_ON_STARTUP config not passed to airbyte-bootloader

### ISSUE THREAD

**Issue by lihan** [airbytehq/helm-charts#8]
Helm chart version

## Environment
- **Airbyte version**:  0.40.27
- **Deployment**: Helm Chart 0.43.18

## Current Behavior
RUN_DATABASE_MIGRATION_ON_STARTUP not passed to `airbyte-bootloader` Pod.
This causes the Airbyte upgrade to fail

## Are you willing to submit a PR?

Yes

**Comment by davinchia** [comment]
Can you please try this on the latest version? If this still exists please open an issue on https://github.com/airbytehq/airbyte. Thank you!
