### ISSUE TITLE
Missing STRICT_COMPARISON_NORMALIZATION_TAG and STRICT_COMPARISON_NORMALIZATION_WORKSPACES in airbyte-env

### ISSUE THREAD

**Issue by yuriolive** [airbytehq/helm-charts#9]
# Environment
Airbyte version: 0.40.32
Deployment: Helm Chart 0.43.33

# Current Behavior
STRICT_COMPARISON_NORMALIZATION_TAG and STRICT_COMPARISON_NORMALIZATION_WORKSPACES are not present in airbyte-env ConfigMap.

This causes the Airbyte to fail to deploy airbyte-worker.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/10088631/217996855-619004c3-93be-46b4-a21e-3d5b48a44f2b.png">

# Are you willing to submit a PR?
Yes

**Comment by yuriolive** [comment]
Issue was solved recreating the cluster, was probably some issue relating upgrading versions.

**Comment by qimumu9406** [comment]
@yuriolive  If you have more free time, please assign this issue to me.

**Comment by yuriolive** [comment]
@qimumu9406 Hi, I think the issue was fixed with this PR https://github.com/airbytehq/airbyte/issues/22687#event-8571554789

**Comment by qimumu9406** [comment]
@yuriolive hi yuriolive
,I think so too, but the kubernetes helm source code has been migrated from the airbyte project to the airbyte-platform project, so I think you need to submit the code again in the airbyte-platform project, and you need to compile or package the kubernets helm source code.

**Comment by michaelbiriley** [comment]
Yes please. Its not in airbyte-0.44.1.tar.gz chart.

**Comment by qimumu9406** [comment]
#10

**Comment by davinchia** [comment]
Migrated to https://github.com/airbytehq/airbyte/issues/25189
